config:
  credentials: []
  project_repos: {}
environment:
  IM_AUTH: val1
sqa_criteria:
  qc_style:
    repos:
      this_repo:
        commands:
        - list -r http://appsgrycap.i3m.upv.es:31443/im-dev/
        container: imservice
timeout: 600
