config:
  credentials: []
  project_repos: {}
environment:
  IM_AUTH: val1
sqa_criteria:
  qc_style:
    repos:
      this_repo:
        commands:
        - echo $IM_AUTH
        - echo $VAL2
        container: imservice
timeout: 600
