config:
  credentials: []
  project_repos: {}
environment:
  IM_AUTH: |
    type = InfrastructureManager; username = micafer; password = alguna
sqa_criteria:
  qc_style:
    repos:
      this_repo:
        commands:
        - im_client.py list -r http://appsgrycap.i3m.upv.es:31443/im-dev/ -a /tmp/auth.dat
        container: imservice
timeout: 600
