services:
  imclient:
    command: sleep 6000000
    environment:
      VAL2: vale23
    image: grycap/in-client
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
