services:
  imservice:
    entrypoint: /bin/sh
    command: -c "sleep 6000000"
    image: grycap/im-client
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
